FROM ubuntu:20.04

ENV container=docker LANG=C.UTF-8

# Enable all repositories
RUN sed -i 's/# deb/deb/g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    dbus systemd systemd-cron rsyslog iproute2 python python-apt sudo bash ca-certificates \
    openssh-server cockpit firewalld ipset python3 iproute2 inetutils-ping vim && \
    apt-get clean && \
    rm -rf /usr/share/doc/* /usr/share/man/* /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN sed -i 's/^\(module(load="imklog")\)/#\1/' /etc/rsyslog.conf

# /usr/share/dbus-1/system.conf
RUN sed -i 's/<!-- <limit name="max_replies_per_connection">128<\/limit> -->/<limit name="max_replies_per_connection">5000<\/limit>/' /usr/share/dbus-1/system.conf

# Don't start any optional services except for the few we need.
#RUN find /etc/systemd/system \
#    /lib/systemd/system \
#    -path '*.wants/*' \
#    -not -name '*dbus*' \
#    -not -name '*journald*' \
#    -not -name '*systemd-tmpfiles*' \
#    -not -name '*systemd-user-sessions*' \
#    -exec rm \{} \;

RUN systemctl set-default multi-user.target
RUN systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount

VOLUME ["/sys/fs/cgroup", "/tmp", "/run", "/run/lock"]
STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init", "--log-target=journal"]
#RUN apt-get update && apt-get install -y openssh-server iproute2 iptables inetutils-ping python cockpit firewalld
#COPY cracker-entrypoint.sh /usr/local/bin/
#RUN mkdir /var/run/sshd
# TODO: change with green team public key
#RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
#RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

#ENV NOTVISIBLE "in users profile"
#RUN echo "export VISIBLE=now" >> /etc/profile

#EXPOSE 22
#ENTRYPOINT /usr/local/bin/cracker-entrypoint.sh
